
spring:
  datasource:
    url: jdbc:mysql://12.12.12.100/project
    username: test1
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
